classOrder = [
    "PakNet",
    "RemoteSettings",
    "Server",
    "Client"
]

gitSourceBranch = "main"

[home]
enabled = true
includeReadme  = true

[[home.features]]
title = "Efficient packet encoding"
description = "PakNet delivers outstanding serialization efficiency through its smart use of Schemas, significantly reducing network bandwidth compared to Roblox’s built-in methods. Its extensive support for various datatypes and structures makes representing complex data both simple and robust."

[[home.features]]
title = "Versatile API"
description = "PakNet provides a straightforward yet versatile API for creating and using remotes. While mimicking the simplicity of Roblox’s default RemoteEvents, it also addresses their pitfalls by handling RemoteFunction timeouts and offering a promisified Invoke method."

[[home.features]]
title = "Exploit resistant"
description = "PakNet strengthens security by ensuring remotes adhere to defined schemas and by offering server-side events that flag network tampering. It also hinders tools like RemoteSpy by hashing remote names and using a binary format, deterring exploiters and protecting network integrity."

[[navbar.items]]
href = "https://wally.run/package/isoopod/paknet"
label = "Wally"
position = "right"