[package]
name = "isoopod/paknet"
description = "Schematized networking library."
version = "0.1.3"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/isoopod/PakNet"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml", "LICENSE"]

[dependencies]
pack = "isoopod/pack@0.5.1"
lemonsignal = "data-oriented-house/lemonsignal@1.10.0"
typed-promise = "lukadev-0/typed-promise@4.0.2"
