[package]
name = "isoopod/paknet"
description = "Schematized networking library."
version = "0.5.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/isoopod/PakNet"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml", "LICENSE"]

[dependencies]
Pack = "isoopod/pack@0.9.2"
Signal = "data-oriented-house/lemonsignal@1.10.0"
Promise = "howmanysmall/typed-promise@4.0.6"
